/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofarmacia;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author Joel Arriola
 */
public class ComprasRealizar extends javax.swing.JFrame {

    /**
     * Creates new form Procuctos
     */
  Conexion conectar=new Conexion();
  Connection ConectarBD=conectar.getConection();
  ResultSet rs;
  PreparedStatement insertar;
  PreparedStatement Actualizar;
  Statement st;
    public ComprasRealizar() {
        initComponents();
        CargarDatosConbox(conMarca);
        CargarDatosLaboratorios(conLaboratorio);
        CargarTipoPago(conPgo);
        CargarCodigoProducto(CodigoProductosCon);
        CargarCodigoCompras(CodigoCompras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComprasTB = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtExistencia = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtCostoTotal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        txtidCompra = new javax.swing.JTextField();
        Comprar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        conLaboratorio = new javax.swing.JComboBox<>();
        conPgo = new javax.swing.JComboBox<>();
        conMarca = new javax.swing.JComboBox<>();
        txtFecha = new com.toedter.calendar.JDateChooser();
        Menu = new javax.swing.JComboBox<>();
        MenuVerDatos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        CodigoProductosCon = new javax.swing.JComboBox<>();
        CodigoCompras = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        ComprasTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ComprasTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprasTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ComprasTB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1190, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Nuevo Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 50));

        txtExistencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Existencia"));
        jPanel2.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 140, 57));

        txtPrecioVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio Venta"));
        jPanel2.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 140, 57));

        txtCosto.setBorder(javax.swing.BorderFactory.createTitledBorder("Costo"));
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 140, 57));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, 57));

        txtNombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Producto"));
        jPanel2.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, 57));

        txtCostoTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Costo Total"));
        jPanel2.add(txtCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 140, 57));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 140, 57));

        txtPrecioCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio Compra"));
        txtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraActionPerformed(evt);
            }
        });
        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 57));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 57));

        txtNit.setBorder(javax.swing.BorderFactory.createTitledBorder("Nit"));
        jPanel2.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 57));

        txtNombreProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Proveedor"));
        jPanel2.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 57));

        txtidCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("codigo Compra"));
        jPanel2.add(txtidCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 57));

        Comprar.setText("Realizar compra");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        jPanel2.add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, 50));

        jButton3.setText("VER COMPRAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, 50));

        jPanel2.add(conLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 170, 57));

        jPanel2.add(conPgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 170, 57));

        jPanel2.add(conMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, 57));

        txtFecha.setDateFormatString("yyy-MM-dd");
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 57));

        Menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Que datos desa agregar", "Nuevo Producto", "Agrege Datos Del Proveedor", "Agregar Compras", "Agregar Detalle Compra", "Nueva Marca De producto" }));
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 140, 60));

        MenuVerDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Datos", "Ver Proveedor", "Ver Productos", "Ver Compras", "Ver Detalles de la Compra" }));
        MenuVerDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuVerDatosMouseClicked(evt);
            }
        });
        MenuVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerDatosActionPerformed(evt);
            }
        });
        jPanel2.add(MenuVerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 140, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 30, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 150, 57));

        CodigoProductosCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoProductosConActionPerformed(evt);
            }
        });
        jPanel2.add(CodigoProductosCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, 50));

        jPanel2.add(CodigoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 140, 50));

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       InsertarProveedor();
       InsertarCompra();
       InsertarNuevoProducto();
       InsertarCompraDEtalle();
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComprasTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasTBMouseClicked
        // TODO add your handling code here:
        int fila=this.ComprasTB.getSelectedRow();
        this.txtidCompra.setText(this.ComprasTB.getValueAt(fila, 0).toString());
        this.txtNombreProveedor.setText(this.ComprasTB.getValueAt(fila, 1).toString());
        this.txtNit.setText(this.ComprasTB.getValueAt(fila, 2).toString());
        this.txtTelefono.setText(this.ComprasTB.getValueAt(fila, 3).toString());
        this.txtPrecioCompra.setText(this.ComprasTB.getValueAt(fila, 4).toString());
        this.txtCantidad.setText(this.ComprasTB.getValueAt(fila, 5).toString());
        this.txtCostoTotal.setText(this.ComprasTB.getValueAt(fila, 6).toString());
        this.txtFecha.setToolTipText(this.ComprasTB.getValueAt(fila, 7).toString());
        this.CodigoProductosCon.setSelectedItem(this.ComprasTB.getValueAt(fila, 8).toString());
        this.txtNombreProducto.setText(this.ComprasTB.getValueAt(fila, 9).toString());
        this.txtDescripcion.setText(this.ComprasTB.getValueAt(fila, 10).toString());
        this.txtCosto.setText(this.ComprasTB.getValueAt(fila, 11).toString());
        this.txtPrecioVenta.setText(this.ComprasTB.getValueAt(fila, 12).toString());
        this.txtExistencia.setText(this.ComprasTB.getValueAt(fila, 13).toString());
       this.conMarca.setSelectedItem(this.ComprasTB.getValueAt(fila, 14).toString());
       this.conLaboratorio.setSelectedItem(this.ComprasTB.getValueAt(fila, 15).toString());
       this.conPgo.setSelectedItem(this.ComprasTB.getValueAt(fila, 16).toString());
    }//GEN-LAST:event_ComprasTBMouseClicked

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComprarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
        if(MenuVerDatos.getSelectedItem().equals("Ver Proveedor")){
          Proveedor();
      }if(MenuVerDatos.getSelectedItem().equals("Ver Productos")){
          MetodoMostrar();
      }if(MenuVerDatos.getSelectedItem().equals("Ver Compras")){
          Compra();
      }if(MenuVerDatos.getSelectedItem().equals("Ver Detalles de la Compra")){
          VerDatos();
      
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(validar<'0'||validar>'9')evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        // TODO add your handling code here:
        char valida=evt.getKeyChar();
        if(valida<'0'||valida>'9')evt.consume();
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char valida=evt.getKeyChar();
                if(valida<'0'||valida>'9')evt.consume();
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        
        if(Menu.getSelectedItem().equals("Nuevo Producto")){
            NuevoProducto Producto=new NuevoProducto();
            Producto.setVisible(true);
            
        }if(Menu.getSelectedItem().equals("Agrege Datos Del Proveedor")){
            Proveedor proveedor=new Proveedor();
            proveedor.setVisible(true);
            
        }if(Menu.getSelectedItem().equals("Agregar Compras")){
            Comprass compra=new Comprass();
            compra.setVisible(true);
        
            
        }
    }//GEN-LAST:event_MenuActionPerformed

    private void MenuVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVerDatosActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
             if(JOptionPane.showConfirmDialog(null,"SEGURO QUE DESA SALIR","SALIENDO",JOptionPane.OK_CANCEL_OPTION)==0){
            dispose();
        
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void CodigoProductosConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoProductosConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoProductosConActionPerformed

    private void MenuVerDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVerDatosMouseClicked
      if(MenuVerDatos.getSelectedItem().equals("Ver Proveedor")){
          Proveedor();
      }if(MenuVerDatos.getSelectedItem().equals("Ver Productos")){
          MetodoMostrar();
      }if(MenuVerDatos.getSelectedItem().equals("Ver Compras")){
          Compra();
      }if(MenuVerDatos.getSelectedItem().equals("Ver Detalles de la Compra")){
          VerDatos();
      
    } 
    }//GEN-LAST:event_MenuVerDatosMouseClicked
public void VerDatos(){
    DefaultTableModel Modelo=new DefaultTableModel();
    
    Modelo.addColumn("idCompraDetalle");
    Modelo.addColumn("Nombre");
    Modelo.addColumn("Nit");
    Modelo.addColumn("Telefono");
    Modelo.addColumn("Precio");
    Modelo.addColumn("Cantidad");
    Modelo.addColumn("costoTotal");
    Modelo.addColumn("Fecha");
    Modelo.addColumn("CodigoProducto");
    Modelo.addColumn("Nombre");
    Modelo.addColumn("Descripcion");
    Modelo.addColumn("Costo");
    Modelo.addColumn("Precio");
    Modelo.addColumn("Existencia");
    Modelo.addColumn("Marca");
    Modelo.addColumn("Laboratorio");
    Modelo.addColumn("Pago");
    ComprasTB.setModel(Modelo);
    
    String Consulta="select cd.idCompraDetalle,pr.Nombre,pr.Nit,pr.Telefono,cd.precio,cd.cantidad,cd.costoTotal,c.Fecha,p.idProductos,p.Nombre,p.Descripcion,p.Costo,p.Precio,p.Existencia,m.NombreMarca,l.Nombre,fp.TipoPago\n" +
"from CompraDetalle cd, Compras c, Productos p, Proveedor pr, Marca m, Laboratorio l,formaPago fp\n" +
"where cd.idCompras=c.idCompras and cd.idProductos=p.idProductos  and c.idProveedores=pr.idProveedores and p.idMarca=m.idMarca and p.idLaboratorio=l.idLaboratorio\n" +
"and fp.idFormaPago=pr.idFormaPago";
    
    String Datos[] = new String[17];
    
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(Consulta);
        
        while(rs.next()){
            Datos[0]=rs.getString(1);
            Datos[1]=rs.getString(2);
            Datos[2]=rs.getString(3);
            Datos[3]=rs.getString(4);
            Datos[4]=rs.getString(5);
            Datos[5]=rs.getString(6);
            Datos[6]=rs.getString(7);
            Datos[7]=rs.getString(8);
            Datos[8]=rs.getString(9);
            Datos[9]=rs.getString(10);
            Datos[10]=rs.getString(11);
            Datos[11]=rs.getString(12);
            Datos[12]=rs.getString(13);
            Datos[13]=rs.getString(14);
            Datos[14]=rs.getString(15);
            Datos[15]=rs.getString(16);
            Datos[16]=rs.getString(17);
        
            Modelo.addRow(Datos);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Erro "+ e.toString());
    }
    
    
}
    /**
     * @param args the command line arguments
     */
public void InsertarProveedor(){
    String sql="INSERT INTO Proveedor(Nombre,Nit,Telefono,idFormaPago)values(?,?,?,?)";
    int TipoPago=1+conPgo.getSelectedIndex();
    
    
    try {
        insertar=ConectarBD.prepareStatement(sql);
        insertar.setString(1, txtNombreProveedor.getText());
        insertar.setString(2, txtNit.getText());
        insertar.setString(3, txtTelefono.getText());
        insertar.setInt(4, TipoPago);
        insertar.executeUpdate();
        JOptionPane.showMessageDialog(null,"Agregados Correcto" );
        System.out.println("Pago id es "+TipoPago);
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"error"+e.toString() );
    }
}
public void InsertarCompra(){
    /*
  
    DateFormat dateFormat = new SimpleDateFormat("yyyy/dd/MM HH"); 
     Date fecha = new Date();
     String FechaActual=dateFormat.format(fecha);
    */
     String sql="INSERT INTO Compras(Fecha,idProveedores)values(?,?)";
    String FechaA=((JTextField)txtFecha.getDateEditor().getUiComponent()).getText();
     
    try {
        insertar=ConectarBD.prepareStatement(sql);
        insertar.setString(1, FechaA);
        insertar.setString(2, txtidCompra.getText());
        insertar.executeUpdate();
    JOptionPane.showMessageDialog(null,"Agregados Correcto" );
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"error"+e.toString() );
    }
}
public void InsertarMarca(){
    String Consulta="INSERT INTO Marca(NombreMarca)values(?)";
    try {
        insertar=ConectarBD.prepareStatement(Consulta);
     //   insertar.setString(1, txtMarca);
    } catch (Exception e) {
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            FlatMaterialLighterIJTheme.setup();
   
       UIManager.put( "Button.arc", 999 );
       UIManager.put( "Component.arc", 999 );
       UIManager.put( "ProgressBar.arc", 999 );
       UIManager.put( "TextComponent.arc", 999 );
       UIManager.put( "ScrollBar.showButtons", true );
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprasRealizar().setVisible(true);
            }
        });
    }
    public void InsertarCompraDEtalle(){
        String insertarDatos="insert into CompraDetalle(idCompras,idProductos,precio,cantidad,costoTotal)values(?,?,?,?,?)";
        float CostoTotal1=Float.valueOf(txtPrecioCompra.getText());
        float Costototal2=Float.valueOf(txtCantidad.getText());
        float Resul=CostoTotal1*Costototal2;
        int CodigoProducto=1+CodigoProductosCon.getSelectedIndex();
        try {
            insertar=ConectarBD.prepareStatement(insertarDatos);
            insertar.setString(1, txtidCompra.getText());
            insertar.setInt(2, CodigoProducto);
            insertar.setString(3, txtPrecioCompra.getText());
            insertar.setString(4, txtCantidad.getText());
            insertar.setFloat(5, Resul);
            insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Agregados Correctamente");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eroror"+e.toString());
        }
    
    }
     
    public void InsertarNuevoProducto(){
        String Consulta="INSERT INTO Productos(Nombre,Descripcion,Costo,Precio,Existencia,idLaboratorio,idMarca)values(?,?,?,?,?,?,?)";
       int laboratorio=1+conLaboratorio.getSelectedIndex();
       int Marca=1+conMarca.getSelectedIndex();
        try {
            insertar=ConectarBD.prepareStatement(Consulta);
            insertar.setString(1, txtNombreProducto.getText());
            insertar.setString(2, txtDescripcion.getText());
            insertar.setString(3, txtCosto.getText());
            insertar.setString(4, txtPrecioVenta.getText());
            insertar.setString(5, txtExistencia.getText());
            insertar.setInt(6, laboratorio);
            insertar.setInt(7,Marca);
            insertar.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Agregados");
            
            System.out.println("id marca"+Marca+" id Laboratorio "+ laboratorio);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
        
    }
    public void MetodoMostrar(){
        DefaultTableModel Modelo=new  DefaultTableModel();
        Modelo.addColumn("Codigo Producto");
        Modelo.addColumn("Nombre Producto");
        Modelo.addColumn("Descripcion");
        Modelo.addColumn("Costo");
        Modelo.addColumn("Precio");
        Modelo.addColumn("Existencia");
        Modelo.addColumn("Laboratorio");
        Modelo.addColumn("Marca");
        ComprasTB.setModel(Modelo);
        String consulta=" select p.idProductos, p.Nombre,p.Descripcion,p.Costo,p.Precio,p.Existencia,l.Nombre,m.NombreMarca\n" +
"from Productos p, Marca m, Laboratorio l\n" +
"where p.idLaboratorio=l.idLaboratorio and p.idMarca=m.idMarca";
        String Datos[]=new String[8];
        
        try {
            st=ConectarBD.createStatement();
            rs=st.executeQuery(consulta);
            while(rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6);
                Datos[6]=rs.getString(7);
                Datos[7]=rs.getString(8);
                Modelo.addRow(Datos);
            }
        } catch (Exception e) {
        }
        
    }
    public void Proveedor(){
        DefaultTableModel Modelo=new DefaultTableModel();
        Modelo.addColumn("Codigo Proveedor");
        Modelo.addColumn("Nombre Proveedor");
        Modelo.addColumn("Nit ");
        Modelo.addColumn("Telefono");
        Modelo.addColumn("Forma de Pago");
        ComprasTB.setModel(Modelo);
        String Datos[]=new String[5];
        String Consulta="select p.idProveedores,p.Nombre,p.Nit,p.Telefono,fp.TipoPago\n" +
"from Proveedor p, formaPago fp\n" +
"where p.idFormaPago=fp.idFormaPago";
        
        try {
            st=ConectarBD.createStatement();
            rs=st.executeQuery(Consulta);
            while(rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Modelo.addRow(Datos);
                
            }
        } catch (Exception e) {
        }
    }
    public void Compra(){
        DefaultTableModel Modelo=new DefaultTableModel();
        Modelo.addColumn("Numero de Compra");
        Modelo.addColumn("Fecha Compra");
        Modelo.addColumn("Codigo Proveedor");
        ComprasTB.setModel(Modelo);
        String Consulta="SELECT *FROM Compras";
        String Datos[]=new String[3];
        
        try {
             st=ConectarBD.createStatement();
            rs=st.executeQuery(Consulta);
            while(rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Modelo.addRow(Datos);
            }
            
        } catch (Exception e) {
        }
    }
    public void CargarDatosConbox(JComboBox marcas){
    DefaultComboBoxModel Datos=new DefaultComboBoxModel();
    
    marcas.setModel(Datos);
    String consulta="select NombreMarca\n" +
"from Marca";
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(consulta);
        while(rs.next()){
          marcas.addItem(rs.getString("NombreMarca"));
            
        }
    } catch (Exception e) {
    }
   
    
    
}
public void CargarDatosLaboratorios(JComboBox Laboratorio){
    DefaultComboBoxModel Labor=new DefaultComboBoxModel();
    Laboratorio.setModel(Labor);
    String consulta="SELECT Nombre from Laboratorio";
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(consulta);
        while(rs.next()){
            Laboratorio.addItem(rs.getString("Nombre"));
        }
    } catch (Exception e) {
    }
    
}
public void CargarTipoPago(JComboBox Pago){
    DefaultComboBoxModel pag=new DefaultComboBoxModel();
    Pago.setModel(pag);
    String Consulta="select TipoPago from formaPago";
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(Consulta);
        while(rs.next()){
            Pago.addItem(rs.getString("TipoPago"));
            
        }
    } catch (Exception e) {
    }
    
}
public void CargarCodigoProducto(JComboBox Codigo){
    DefaultComboBoxModel CodigModel=new DefaultComboBoxModel();
    Codigo.setModel(CodigModel);
    String consulta="select idProductos from Productos";
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(consulta);
        while(rs.next()){
            Codigo.addItem(rs.getString("idProductos"));
        }
    } catch (Exception e) {
    }
    
}

public void CargarCodigoCompras(JComboBox CodigoCompras){
    DefaultComboBoxModel CodigoCompraModelo=new DefaultComboBoxModel();
       CodigoCompras.setModel(CodigoCompraModelo);
       String Consulta="select idCompras from Compras";
       try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(Consulta);
        while(rs.next()){
            this.CodigoCompras.addItem(rs.getString("idCompras"));
        }
    } catch (Exception e) {
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CodigoCompras;
    private javax.swing.JComboBox<String> CodigoProductosCon;
    private javax.swing.JButton Comprar;
    private javax.swing.JTable ComprasTB;
    private javax.swing.JPanel Fondo;
    private javax.swing.JComboBox<String> Menu;
    private javax.swing.JComboBox<String> MenuVerDatos;
    private javax.swing.JComboBox<String> conLaboratorio;
    private javax.swing.JComboBox<String> conMarca;
    private javax.swing.JComboBox<String> conPgo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtidCompra;
    // End of variables declaration//GEN-END:variables
}
