/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofarmacia;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class Comprass extends javax.swing.JFrame {

    Conexion conectar=new Conexion();
    Connection conectarBD=conectar.getConection();
    ResultSet rs;
    PreparedStatement Insertar;
    PreparedStatement Actualiza;
    Statement st;
    public Comprass() {
        initComponents();
        CargarDatosCodgoProveedor(CodigoProveedor);
        VerCompras();
        ActualizarBoton.setEnabled(false);
        AutoCompleteDecorator.decorate(CodigoProveedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        DateFecha = new com.toedter.calendar.JDateChooser();
        CodigoProveedor = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        ActualizarBoton = new javax.swing.JButton();
        NuevaCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCompras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fondo.setBackground(new java.awt.Color(0, 204, 204));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 207, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateFecha.setDateFormatString("yyy-MM-dd");
        DateFecha.setName("yyy-MM-dd"); // NOI18N
        DateFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateFechaMouseClicked(evt);
            }
        });
        jPanel1.add(DateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 167, 140, 40));

        CodigoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoProveedorMouseClicked(evt);
            }
        });
        jPanel1.add(CodigoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 238, 140, 40));

        txtID.setEditable(false);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 72, 140, 44));

        ActualizarBoton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ActualizarBoton.setForeground(new java.awt.Color(0, 0, 0));
        ActualizarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        ActualizarBoton.setText("ACTUALIZAR FECHA COMPRA");
        ActualizarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 160, 300, 70));

        NuevaCompra.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        NuevaCompra.setForeground(new java.awt.Color(0, 0, 0));
        NuevaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_1.png"))); // NOI18N
        NuevaCompra.setText("REGISTRAR FECHA DE COMPRA");
        NuevaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCompraActionPerformed(evt);
            }
        });
        jPanel1.add(NuevaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 80, 300, 70));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 167, 140, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo Proveedor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 246, 140, 40));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CodigoCompra");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 76, 140, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 50, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarVentana.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        TablaCompras.setForeground(new java.awt.Color(0, 0, 0));
        TablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCompras);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 790, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaComprasMouseClicked
        ActualizarBoton.setEnabled(true);
        
        NuevaCompra.setEnabled(false);
        int fila=this.TablaCompras.getSelectedRow();
        this.txtID.setText(this.TablaCompras.getValueAt(fila, 0).toString());
        this.DateFecha.setDateFormatString(this.TablaCompras.getValueAt(fila, 1).toString());
        this.CodigoProveedor.setSelectedItem(this.TablaCompras.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_TablaComprasMouseClicked

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
       ActualizarFecha();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void NuevaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCompraActionPerformed
       String FechaA=((JTextField)DateFecha.getDateEditor().getUiComponent()).getText(); 
        
        if(FechaA.trim().isEmpty()){
              JOptionPane.showMessageDialog(null,"LLENAR CAMPOS OBLIGATORIOS","ERROR",JOptionPane.YES_NO_OPTION);
        }else{
        InsertarCompra();
        }
        
        
     
       

    }//GEN-LAST:event_NuevaCompraActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        NuevaCompra.setEnabled(true);
        CodigoProveedor.setEnabled(true);
        ActualizarBoton.setEnabled(false);
        
        
                
                
                
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
         CodigoProveedor.setEnabled(true);
    }//GEN-LAST:event_txtIDMouseClicked

    private void DateFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFechaMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        //Minimizar ventana
        this.setState(Clientes.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(JOptionPane.showConfirmDialog(null,"DESEA SALIR DE LA VENTANA CLIENTES","SALIR",JOptionPane.YES_NO_OPTION)==0){
            dispose();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void CodigoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoProveedorMouseClicked
      
    }//GEN-LAST:event_CodigoProveedorMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void CargarDatosCodgoProveedor(JComboBox CodigoProveedor){
        DefaultComboBoxModel Codigo=new DefaultComboBoxModel();
        CodigoProveedor.setModel(Codigo);
        String Consulta="select idProveedores from Proveedor";
        try {
        st=conectarBD.createStatement();
        rs=st.executeQuery(Consulta);
        while(rs.next()){
            CodigoProveedor.addItem(rs.getString("IdProveedores"));
            
        }
        } catch (Exception e) {
        }
        
        
        
        
    }
    
    public void VerCompras(){
        DefaultTableModel Modelo=new DefaultTableModel();
        Modelo.addColumn("Codigo Compras");
        Modelo.addColumn("Fecha");
        Modelo.addColumn("Codigo Proveedor");
        Modelo.addColumn("Proveedor");
        TablaCompras.setModel(Modelo);
        
        String consulta="Select c.idCompras,c.Fecha,p.idProveedores,p.Nombre\n" +
"from Compras c , Proveedor p\n" +
"where c.idProveedores=p.idProveedores\n" +
"order by idCompras desc";
        String Dato[]=new String[4];
        try {
            st=conectarBD.createStatement();
            rs=st.executeQuery(consulta);
            while(rs.next()){
                Dato[0]=rs.getString(1);
                Dato[1]=rs.getString(2);
                Dato[2]=rs.getString(3);
                Dato[3]=rs.getString(4);
                Modelo.addRow(Dato);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+ e.toString());
        }
    }
    public void limpiar(){
        txtID.setText("");
        DateFecha.setDateFormatString("");
        CodigoProveedor.setSelectedItem(0);
    }
    public void InsertarCompra(){
    /*
  
    DateFormat dateFormat = new SimpleDateFormat("yyyy/dd/MM HH"); 
     Date fecha = new Date();
     String FechaActual=dateFormat.format(fecha);
    */
     String sql="INSERT INTO Compras(Fecha,idProveedores)values(?,?)";
    String FechaA=((JTextField)DateFecha.getDateEditor().getUiComponent()).getText();
    String Datos=(String) CodigoProveedor.getSelectedItem();
    int Codigo=Integer.parseInt(Datos);
    
        System.out.println("El codigo es"+Codigo);
    try {
        Insertar=conectarBD.prepareStatement(sql);
        Insertar.setString(1, FechaA);
        Insertar.setInt(2,Codigo);
        Insertar.executeUpdate();
    VerCompras();
    //.showMessageDialog(null,"Agregados Correcto" );
       
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"error"+e.toString() );
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();
   
       UIManager.put( "Button.arc", 999 );
       UIManager.put( "Component.arc", 999 );
       UIManager.put( "ProgressBar.arc", 999 );
       UIManager.put( "TextComponent.arc", 999 );
       UIManager.put( "ScrollBar.showButtons", true );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprass().setVisible(true);
            }
        });
    }
    
    public void ActualizarFecha(){
         String FechaA=((JTextField)DateFecha.getDateEditor().getUiComponent()).getText(); 
         String CodigoProve=(String)CodigoProveedor.getSelectedItem();
         
        try {
            Actualiza=conectarBD.prepareStatement("update Compras set Fecha='"+FechaA+"',idProveedores='"+CodigoProve+"' where idCompras='"+txtID.getText()+"'");
        int Contador=Actualiza.executeUpdate();
        if(Contador>0){
            VerCompras();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JComboBox<String> CodigoProveedor;
    private com.toedter.calendar.JDateChooser DateFecha;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton NuevaCompra;
    private javax.swing.JTable TablaCompras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
