/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofarmacia;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel Arriola
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Usuario
     */
    Conexion Conectar=new Conexion();
    Connection ConectarBD=Conectar.getConection();
    ResultSet rs;
    PreparedStatement Insertar=null;
    PreparedStatement Actualizar=null;
    PreparedStatement Eliminar=null;
    Statement st;
    
    public Usuario() {
        initComponents();
        jButton1.putClientProperty( "FlatLaf.styleClass", "h1" );
        RegistrarBoto.putClientProperty( "FlatLaf.styleClass", "h1" );
        ActualizarBoto.putClientProperty( "FlatLaf.styleClass", "h1" );
        
    }
    public void VerDatosUsuario(){
        DefaultTableModel Modelo=new DefaultTableModel();
        Modelo.addColumn("idUsuario");
        Modelo.addColumn("NombreUsuario");
        Modelo.addColumn("ApellidoUsuario");
        Modelo.addColumn("Usuario");
        Modelo.addColumn("Contraseña");
        Modelo.addColumn("Cargo");
        Modelo.addColumn("Estado");
        Modelo.addColumn("NivelAcceso");
        DatosUsuarios.setModel(Modelo);
        String Datos[] = new String[8];
        String Consulta="select u.idUsuario,u.NombreUsuario,u.ApellidoUsuario,u.Usuario,u.Contraseña, tu.NombreTipoUsuario As Cargo ,es.NombreEstado as Estado, cu.NombreAcceso as NivelAcceso\n" +
"from Usuario u, TipoUsuario tu, EstadoUsuario es, AccesoUsuario cu\n" +
"where u.idAccesoUsuario=cu.idAccesoUsuario and u.idEstadoUsuario=es.idEstadoUsuario and u.idTipoUsuario=tu.idTipoUsuario";
        try {
            st=ConectarBD.createStatement();
            rs=st.executeQuery(Consulta);
            while(rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6);
                Datos[6]=rs.getString(7);
                Datos[7]=rs.getString(8);
                Modelo.addRow(Datos);
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Parece que tenemos un error"+e.toString());
        }
                
        
        
    }

    public void RegistrarUsuario(){
        String InsertarDatos="INSERT INTO Usuario(NombreUsuario,ApellidoUsuario,Usuario,Contraseña,idTipoUsuario,idEstadoUsuario,idAccesoUsuario)values(?,?,?,?,?,?,?);";
    int Cargo=4;
    
    
        
     {
         
     }
        String Agregar=(String) conCargo.getSelectedItem();
        int indice =conCargo.getSelectedIndex();
        int estado=conEstado.getSelectedIndex();
        int Nivel=conNivel.getSelectedIndex();
       
        
        
        
        try {
            Insertar=ConectarBD.prepareCall(InsertarDatos);
            Insertar.setString(1, txtNombre.getText());
            Insertar.setString(2,txtApellido.getText() );
            Insertar.setString(3,txtUsuario.getText() );
            Insertar.setString(4,txtContra.getText() );
            Insertar.setInt(5,indice);
            Insertar.setInt(6, estado);
            Insertar.setInt(7, Nivel);
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos agregados Correctamente");
            
            Limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ELIMINAR = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        conCargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        conEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        conNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RegistrarBoto = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        ActualizarBoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DatosUsuarios = new javax.swing.JTable();

        jMenuItem1.setLabel("ELIMINAR USUARIO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ELIMINAR.add(jMenuItem1);

        setPreferredSize(new java.awt.Dimension(890, 630));

        Fondo.setBackground(new java.awt.Color(51, 153, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("VER USUARIOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 300, 30));

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 14, 149, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 53, 38));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 38));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 100, 149, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 38));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 58, 152, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cargo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 100, 38));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 149, -1));

        conCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cargo", "Administrador", "Gerente", "Cajero", "Moderador" }));
        jPanel1.add(conCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 150, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 38));

        conEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Estado", "Activo", "Inactivo" }));
        jPanel1.add(conEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 150, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, 38));

        conNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Nivel de Acceso", "Nivel 1", "Nivel 2", "Nivel 3", "Nivel 4", "Nivel 5" }));
        jPanel1.add(conNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 150, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nivel de Acceso");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 100, 38));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 100, 38));

        RegistrarBoto.setText("REGISTRAR USUARIO");
        RegistrarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBotoActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarBoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 30));
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, -1));

        ActualizarBoto.setText("ACTUALIZAR USUARIO");
        ActualizarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotoActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarBoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 30));

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 320));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE LOS USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        DatosUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        DatosUsuarios.setComponentPopupMenu(ELIMINAR);
        DatosUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatosUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DatosUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 890, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VerDatosUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegistrarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBotoActionPerformed
        // TODO add your handling code here:
       RegistrarUsuario();
     
    }//GEN-LAST:event_RegistrarBotoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void DatosUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatosUsuariosMouseClicked
        // TODO add your handling code here:
        ActualizarBoto.setEnabled(true);
        RegistrarBoto.setEnabled(false);
        int filas=this.DatosUsuarios.getSelectedRow();
        this.txtID.setText(this.DatosUsuarios.getValueAt(filas, 0).toString());
        this.txtNombre.setText(this.DatosUsuarios.getValueAt(filas, 1).toString());
        this.txtApellido.setText(this.DatosUsuarios.getValueAt(filas, 2).toString());
        this.txtUsuario.setText(this.DatosUsuarios.getValueAt(filas, 3).toString());
        this.txtContra.setText(this.DatosUsuarios.getValueAt(filas, 4).toString());
        this.conCargo.setSelectedItem(this.DatosUsuarios.getValueAt(filas, 5).toString());
        this.conEstado.setSelectedItem(this.DatosUsuarios.getValueAt(filas, 6).toString());
        this.conNivel.setSelectedItem(this.DatosUsuarios.getValueAt(filas, 7).toString());
    }//GEN-LAST:event_DatosUsuariosMouseClicked

    private void ActualizarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotoActionPerformed
        // TODO add your handling code here:
        ActualizarDatos();
    }//GEN-LAST:event_ActualizarBotoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Esta Seguro de Eliminar Este usuario","ELIMINAR",JOptionPane.YES_NO_CANCEL_OPTION)==0){
            EliminarUsuario();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        RegistrarBoto.setEnabled(true);
        ActualizarBoto.setEnabled(false);
        Limpiar();
    }//GEN-LAST:event_jPanel1MouseClicked
public void EliminarUsuario(){
    try {
        Eliminar=ConectarBD.prepareStatement("Delete from Usuario where idUsuario='"+txtID.getText()+"'");
        int Contador=Eliminar.executeUpdate();
        if(Contador>0){
            JOptionPane.showMessageDialog(null,"USUARIO ELIMINADO CON EXITO");
            VerDatosUsuario();
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione Fila");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error al eliminar"+ e.toString());
    }
}
public void ActualizarDatos(){
      int indice =conCargo.getSelectedIndex();
        int estado=conEstado.getSelectedIndex();
        int Nivel=conNivel.getSelectedIndex();
    try {
        
        Actualizar=ConectarBD.prepareStatement("UPDATE Usuario set NombreUsuario='"+txtNombre.getText()+"',ApellidoUsuario='"+txtApellido.getText()+"',Usuario='"+txtUsuario.getText()+"',Contraseña='"+txtContra.getText()+"',idTipoUsuario='"+indice+"',idEstadoUsuario='"+estado+"',idAccesoUsuario='"+Nivel+"' where idUsuario='"+txtID.getText()+"'");
        int Contador=Actualizar.executeUpdate();
        if(Contador>0){
            JOptionPane.showMessageDialog(null,"Datos Actualizados Correctamente" );
            VerDatosUsuario();
        }else{
            JOptionPane.showMessageDialog(null,"No selecciono la fila " );
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error Al Actualizar"+e.toString());
    }
}
 public void Limpiar(){
     txtID.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtContra.setText("");
        conCargo.setSelectedIndex(0);
        conEstado.setSelectedIndex(0);
        conNivel.setSelectedIndex(0);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoto;
    private javax.swing.JTable DatosUsuarios;
    private javax.swing.JPopupMenu ELIMINAR;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton RegistrarBoto;
    private javax.swing.JComboBox<String> conCargo;
    private javax.swing.JComboBox<String> conEstado;
    private javax.swing.JComboBox<String> conNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
